### ISSUE TITLE
undefined method `provides' for ChefVaultCookbook::Provider::ChefVaultSecret:Class

### ISSUE THREAD

**Issue by pwyliu** [chef-cookbooks/chef-vault#36] opened 2015-10-01 05:52 UTC
Hiya,

I just pulled `chef-vault 1.3.1` from supermarket and I'm getting this error when trying to converge nodes:

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/chef-vault/libraries/chef_vault_secret.rb
================================================================================

NoMethodError
-------------
undefined method `provides' for ChefVaultCookbook::Provider::ChefVaultSecret:Class

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/chef-vault/libraries/chef_vault_secret.rb:48:in `<class:ChefVaultSecret>'
  /var/chef/cache/cookbooks/chef-vault/libraries/chef_vault_secret.rb:47:in `<module:Provider>'
  /var/chef/cache/cookbooks/chef-vault/libraries/chef_vault_secret.rb:46:in `<module:ChefVaultCookbook>'
  /var/chef/cache/cookbooks/chef-vault/libraries/chef_vault_secret.rb:27:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/chef-vault/libraries/chef_vault_secret.rb:

 41:        attribute(:raw_data, kind_of: [Hash, Mash], default: {})
 42:        attribute(:environment, kind_of: [String, NilClass], default: nil)
 43:      end
 44:    end
 45:
 46:    module Provider
 47:      class ChefVaultSecret < Chef::Provider::LWRPBase
 48>>       provides(:chef_vault_secret)
```

The nodes I was having trouble with are running `chef-client 11.8.6`. Reverting to `chef-vault 1.3.0` fixes the issue.

**Comment by christianclarke** [comment] 2015-10-01 09:51
Confirmed the above breaking changes.  We are seeing the same issue.  With Chef-Client 11.18.6.  Our application cookbooks, use the v1.0.0 certificate community cookbook.  The certificate community cookbook pulls in chef-vault.  But the certificate community cookbook has no pinning.  So, it's getting the latest chef-vault.

   ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/chef-vault/libraries/chef_vault_secret.rb
       ================================================================================

       NoMethodError
       -------------
       undefined method `provides' for ChefVaultCookbook::Provider::ChefVaultSecret:Class

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/chef-vault/libraries/chef_vault_secret.rb:48:in `<class:ChefVaultSecret>'
         /tmp/kitchen/cache/cookbooks/chef-vault/libraries/chef_vault_secret.rb:47:in `<module:Provider>'
         /tmp/kitchen/cache/cookbooks/chef-vault/libraries/chef_vault_secret.rb:46:in `<module:ChefVaultCookbook>'
         /tmp/kitchen/cache/cookbooks/chef-vault/libraries/chef_vault_secret.rb:27:in `<top (required)>'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/chef-vault/libraries/chef_vault_secret.rb:

        41:        attribute(:raw_data, kind_of: [Hash, Mash], default: {})
        42:        attribute(:environment, kind_of: [String, NilClass], default: nil)
        43:      end
        44:    end
        45:
        46:    module Provider
        47:      class ChefVaultSecret < Chef::Provider::LWRPBase
        48>>       provides(:chef_vault_secret)
        49:
        50:        use_inline_resources if defined?(:use_inline_resources)
        51:
        52:        def whyrun_supported?
        53:          true
        54:        end
        55:
        56:        def load_current_resource
        57:          json = ChefVault::Item.load(new_resource.data_bag, new_resource.id)


       Running handlers:
       [2015-10-01T08:44:59+01:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-10-01T08:44:59+01:00] ERROR: Exception handlers complete
       [2015-10-01T08:44:59+01:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 0 resources updated in 13.700046969 seconds
       [2015-10-01T08:44:59+01:00] ERROR: undefined method `provides' for ChefVaultCookbook::Provider::ChefVaultSecret:Class
       [2015-10-01T08:44:59+01:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by TylerBJohnson** [comment] 2015-10-01 15:38
It looks like the provides syntax is a Chef 12 feature, I'm not sure how this was released as a patch level release.

**Comment by zgoldman** [comment] 2015-10-01 15:42
More info from chef: https://www.chef.io/blog/2015/02/10/chef-12-provider-resolver/

>LWRP Chef-11 BackCompat

>It turns out that Chef-11 supports the ‘provides’ syntax on resources, so that this feature can be used in community cookbooks and other places where Chef-11 backcompat is still important. Chef-12 simply improved on the API which was already present for Resources. It does not allow the ‘provides’ syntax on Providers, and it only takes an “on_platform:” argument (Chef-12 also supports “on_platform” as an alias for “platform” for back-compat). To rename LWRPs and maintain Chef-11 backcompat simply drop the ‘provides’ line from the Provider, or ideally protect it with an ‘if respond_to?(:provides)’ check.

**Comment by morrissimo** [comment] 2015-10-01 20:46
Same issue here as well - although we ran into it via AWS OpsWorks: running "Setup" on a newly-created instance failed with this error.

**Comment by nothsa** [comment] 2015-10-01 22:10
Running into this same issue. @johnbellone Any chance we can get an ETA on a fix?

**Comment by nothsa** [comment] 2015-10-02 00:20
**Temporary workaround:** I have pinned the chef-vault version to its previous version (1.3.0) and it completes successfully. I then ran into the same issue with chef-splunk on version 1.4.0, so I also pinned that to its previous version (1.3.0), which solved that issue, and now everything boots as normal.

**Comment by morrissimo** [comment] 2015-10-13 20:18
> Temporary workaround: I have pinned the chef-vault version to its previous version (1.3.0) and it completes successfully. I then ran into the same issue with chef-splunk on version 1.4.0, so I also pinned that to its previous version (1.3.0), which solved that issue, and now everything boots as normal.

Same; worked for me as well

**Comment by ljay79** [comment] 2015-10-13 21:01
Using Vagrant with AWS OpsWorks (Chef 11.10.4) and enabled berkshelf, got the same issue and above temp workaround work here as well.

**Comment by johnbellone** [comment] 2015-10-14 13:43
So it looks like this is failing because the provides syntax isn't in Chef 11.

**Closed** 2015-10-22 15:07 UTC
