### ISSUE TITLE
No resource or method named `chef_vault_item' for `Chef::Recipe

### ISSUE THREAD

**Issue by thinkrapido** [chef-cookbooks/chef-vault#52] opened 2016-04-30 09:38 UTC
### Cookbook version

latest
### Chef-client version

12.8.1
### Platform Details

ubuntu 14.04
### Scenario:

Use chef_vault_item method

`No resource or method named`chef_vault_item' for `Chef::Recipe`

What prerequisites do I need to use this method during bootstrapping a node
### Steps to Reproduce:

knife bootstrap ...
### Expected Result:

Method can be used
##

**Comment by cheeseplus** [comment] 2017-04-12 15:55
Given there has been a major version change and this problem doesn't seem present, closing. If the issue is preventing itself in current version please open a new issue.

**Closed by cheeseplus** 2017-04-12 15:55 UTC
